In [11]:
import numpy as np
np.__version__

'2.1.3'

In [12]:
my_list =[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [13]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [14]:
print(type(arr))

<class 'numpy.ndarray'>


In [18]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [20]:
np.arange(10,20,5)

array([10, 15])

In [21]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [22]:
np.arange(20,10)

array([], dtype=int64)

In [23]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [24]:
np.zeros(5) # Parameter tuning

array([0., 0., 0., 0., 0.])

In [26]:
np.zeros(5, dtype = int) #

array([0, 0, 0, 0, 0])

In [27]:
np.zeros([2, 2]) # Hyperparameter tuning

array([[0., 0.],
       [0., 0.]])

In [28]:
np.zeros([5, 4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.zeros(5, dtype = int)

In [29]:
np.ones(2)

array([1., 1.])

In [30]:
np.ones(2, dtype = int)

array([1, 1])

In [31]:
np.ones([2, 2])

array([[1., 1.],
       [1., 1.]])

In [32]:
np.ones([4, 5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [33]:
arr

array([0, 1, 2, 3, 4, 5])

In [34]:
rand(3,2)

NameError: name 'rand' is not defined

In [35]:
random.rand(3,2)

NameError: name 'random' is not defined

In [36]:
np.random.rand(3,2)

array([[0.47675412, 0.73806924],
       [0.54309458, 0.84358012],
       [0.08025155, 0.59297596]])

In [37]:
np.random.rand(3,2)

array([[0.98191852, 0.83354418],
       [0.17405081, 0.49445032],
       [0.22619433, 0.49258645]])

In [39]:
np.random.rand(3)

array([0.01367879, 0.88700888, 0.48393453])

In [42]:
np.random.randint(4,6)

4

In [45]:
np.random.randint(0,10)

6

In [47]:
np.random.randint(0,10,4)

array([5, 3, 2, 5])

In [48]:
np.random.randint(0,10,5)

array([2, 1, 5, 4, 9])

In [53]:
n = np.random.randint(10,40,(8,10))
n

array([[17, 32, 29, 26, 15, 14, 34, 28, 13, 30],
       [32, 29, 25, 22, 31, 31, 30, 16, 30, 24],
       [27, 30, 36, 20, 18, 37, 17, 14, 19, 36],
       [20, 28, 29, 38, 37, 31, 20, 20, 18, 16],
       [29, 28, 32, 39, 18, 24, 18, 38, 23, 34],
       [30, 16, 39, 37, 39, 23, 18, 35, 25, 13],
       [19, 22, 18, 27, 22, 30, 38, 20, 17, 37],
       [13, 27, 39, 23, 37, 26, 27, 20, 29, 23]])

In [54]:
n[0]

array([17, 32, 29, 26, 15, 14, 34, 28, 13, 30])

In [55]:
n[5]

array([30, 16, 39, 37, 39, 23, 18, 35, 25, 13])

In [56]:
n

array([[17, 32, 29, 26, 15, 14, 34, 28, 13, 30],
       [32, 29, 25, 22, 31, 31, 30, 16, 30, 24],
       [27, 30, 36, 20, 18, 37, 17, 14, 19, 36],
       [20, 28, 29, 38, 37, 31, 20, 20, 18, 16],
       [29, 28, 32, 39, 18, 24, 18, 38, 23, 34],
       [30, 16, 39, 37, 39, 23, 18, 35, 25, 13],
       [19, 22, 18, 27, 22, 30, 38, 20, 17, 37],
       [13, 27, 39, 23, 37, 26, 27, 20, 29, 23]])

In [57]:
n[0:6]

array([[17, 32, 29, 26, 15, 14, 34, 28, 13, 30],
       [32, 29, 25, 22, 31, 31, 30, 16, 30, 24],
       [27, 30, 36, 20, 18, 37, 17, 14, 19, 36],
       [20, 28, 29, 38, 37, 31, 20, 20, 18, 16],
       [29, 28, 32, 39, 18, 24, 18, 38, 23, 34],
       [30, 16, 39, 37, 39, 23, 18, 35, 25, 13]])

In [58]:
n

array([[17, 32, 29, 26, 15, 14, 34, 28, 13, 30],
       [32, 29, 25, 22, 31, 31, 30, 16, 30, 24],
       [27, 30, 36, 20, 18, 37, 17, 14, 19, 36],
       [20, 28, 29, 38, 37, 31, 20, 20, 18, 16],
       [29, 28, 32, 39, 18, 24, 18, 38, 23, 34],
       [30, 16, 39, 37, 39, 23, 18, 35, 25, 13],
       [19, 22, 18, 27, 22, 30, 38, 20, 17, 37],
       [13, 27, 39, 23, 37, 26, 27, 20, 29, 23]])

In [59]:
n[::-1]

array([[13, 27, 39, 23, 37, 26, 27, 20, 29, 23],
       [19, 22, 18, 27, 22, 30, 38, 20, 17, 37],
       [30, 16, 39, 37, 39, 23, 18, 35, 25, 13],
       [29, 28, 32, 39, 18, 24, 18, 38, 23, 34],
       [20, 28, 29, 38, 37, 31, 20, 20, 18, 16],
       [27, 30, 36, 20, 18, 37, 17, 14, 19, 36],
       [32, 29, 25, 22, 31, 31, 30, 16, 30, 24],
       [17, 32, 29, 26, 15, 14, 34, 28, 13, 30]])

In [60]:
n

array([[17, 32, 29, 26, 15, 14, 34, 28, 13, 30],
       [32, 29, 25, 22, 31, 31, 30, 16, 30, 24],
       [27, 30, 36, 20, 18, 37, 17, 14, 19, 36],
       [20, 28, 29, 38, 37, 31, 20, 20, 18, 16],
       [29, 28, 32, 39, 18, 24, 18, 38, 23, 34],
       [30, 16, 39, 37, 39, 23, 18, 35, 25, 13],
       [19, 22, 18, 27, 22, 30, 38, 20, 17, 37],
       [13, 27, 39, 23, 37, 26, 27, 20, 29, 23]])

In [61]:
n[::2]

array([[17, 32, 29, 26, 15, 14, 34, 28, 13, 30],
       [27, 30, 36, 20, 18, 37, 17, 14, 19, 36],
       [29, 28, 32, 39, 18, 24, 18, 38, 23, 34],
       [19, 22, 18, 27, 22, 30, 38, 20, 17, 37]])

In [62]:
n

array([[17, 32, 29, 26, 15, 14, 34, 28, 13, 30],
       [32, 29, 25, 22, 31, 31, 30, 16, 30, 24],
       [27, 30, 36, 20, 18, 37, 17, 14, 19, 36],
       [20, 28, 29, 38, 37, 31, 20, 20, 18, 16],
       [29, 28, 32, 39, 18, 24, 18, 38, 23, 34],
       [30, 16, 39, 37, 39, 23, 18, 35, 25, 13],
       [19, 22, 18, 27, 22, 30, 38, 20, 17, 37],
       [13, 27, 39, 23, 37, 26, 27, 20, 29, 23]])

In [63]:
n[0]

array([17, 32, 29, 26, 15, 14, 34, 28, 13, 30])

In [64]:
n

array([[17, 32, 29, 26, 15, 14, 34, 28, 13, 30],
       [32, 29, 25, 22, 31, 31, 30, 16, 30, 24],
       [27, 30, 36, 20, 18, 37, 17, 14, 19, 36],
       [20, 28, 29, 38, 37, 31, 20, 20, 18, 16],
       [29, 28, 32, 39, 18, 24, 18, 38, 23, 34],
       [30, 16, 39, 37, 39, 23, 18, 35, 25, 13],
       [19, 22, 18, 27, 22, 30, 38, 20, 17, 37],
       [13, 27, 39, 23, 37, 26, 27, 20, 29, 23]])

In [65]:
n[0,5]

np.int64(14)

In [66]:
n[0,5]

np.int64(14)

In [67]:
n[5,-3]

np.int64(35)

In [73]:
a = n[0,5]
print(a)

14


In [74]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [77]:
np.arange(1,13).reshape(5,5)

ValueError: cannot reshape array of size 12 into shape (5,5)

In [79]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])