# Indexing

In [3]:
import numpy as np

In [4]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [5]:
row = 4
col = 5
col

5

In [6]:
row

4

In [7]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [8]:
mat[row,col]
print(mat)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [9]:
mat[4,5]

np.int64(45)

In [10]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [11]:
mat[7]

array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79])

In [12]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [13]:
mat[:,col]

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [14]:
mat[col]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [15]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [16]:
mat[:, -1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [17]:
mat[:, 3]

array([ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93])

In [18]:
row

4

In [19]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [20]:
mat[4,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [21]:
mat[3,:]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [22]:
mat[:,5]

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [23]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [24]:
mat[:col]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [25]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [26]:
mat[2:6,2:4]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [27]:
mat[2:4,3:5]

array([[23, 24],
       [33, 34]])

# Masking

In [28]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [29]:
mat[mat < 50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [30]:
mat[mat == 50]

array([50])

In [31]:
mat[mat != 50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

# 1. Array Creation Function

In [32]:
# Create an array frim list 
a = np.array([1,2,3])
print("array a:",a)

array a: [1 2 3]


In [33]:
# Create an array with evenly spaced values
b = np.arange(0, 10,2) # Values from 0 to 10 with step 2
print("array b:", b)

array b: [0 2 4 6 8]


In [37]:
# Create an array with linearly spaced values
c = np.linspace(0,1,5) # 5 values evenlyspaced between 0 and 1
print("array c:",c)


array c: [0.   0.25 0.5  0.75 1.  ]


In [38]:
# Create an array filled with zeros
d = np.zeros((2,3)) # 2 x 3 array of zeros
print("array d:",d)


array d: [[0. 0. 0.]
 [0. 0. 0.]]


In [39]:
# Create an array filled with ones
e = np.ones((3, 2))  # 3x2 array of ones
print("Array e:\n", e)

Array e:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [40]:
# Create an identity matrix
f = np.eye(4)  # 4x4 identity matrix
print("Identity matrix f:\n", f)

Identity matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# 2.Array Manipulation Functions

In [48]:
#  Reshape an array
a1= np.array([1,2,3])
reshaped = np.reshape(a1, (1,3))  # reshape to 1X 3
print("Reshaped array:", reshaped)

Reshaped array: [[1 2 3]]


In [50]:
#  Flatten an array
f1 = np.array([[1,2],[3,4]])
flattened = np.ravel(f1)  # flatten to 1D array
print("Flattend array:", flattened)

Flattend array: [1 2 3 4]


In [51]:
# Transpose an array
e1 = np.array([[1, 2], [3, 4]])
transposed = np.transpose(e1)  # Transpose the array
print("Transposed array:\n", transposed)

Transposed array:
 [[1 3]
 [2 4]]


In [52]:
# Stack arrays vertically
a2 = np.array([1, 2])
b2 = np.array([3, 4])
stacked = np.vstack([a2, b2])  # Stack a and b vertically
print("Stacked arrays:\n", stacked)

Stacked arrays:
 [[1 2]
 [3 4]]


# 3. Mathematical Functions

In [53]:
#  Add two arrays
g = np.array([1,2,3,4])
added = np.add(g, 2)  # Add 2 to each element
print("Added 2 to g:", added)

Added 2 to g: [3 4 5 6]


In [59]:
#  Square each element
squared  = np.power(g, 2) # square each element
print("Squared g:", squared)

Squared g: [ 1  4  9 16]


In [60]:
# Square root of each element
sqrt_val = np.sqrt(g)  # Square root of each element
print("Square root of g:", sqrt_val)

Square root of g: [1.         1.41421356 1.73205081 2.        ]


In [61]:
print(a1)
print(g)

[1 2 3]
[1 2 3 4]


In [62]:
# Dot product of two arrays
a2 = np.array([1, 2, 3])
dot_product = np.dot(a2, g)  # Dot product of a and g
print("Dot product of a and g:", dot_product)

ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)

In [63]:
print(a)
print(a1)

[1 2 3]
[1 2 3]


In [64]:
a3 = np.array([1, 2, 3])
dot_product = np.dot(a1, a)  # Dot product of a and g
print("Dot product of a1 and a:", dot_product)

Dot product of a1 and a: 14


# 4. Statstical Functions

In [65]:
s = np.array([1,2,3,4])
mean = np.mean(s)
print("Mean of s:", mean)

Mean of s: 2.5


In [66]:
# Standard deviation of an array
std_dev = np.std(s)
print("Standard deviation of s:", std_dev)

Standard deviation of s: 1.118033988749895


In [67]:
# Minimum element of an array
minimum = np.min(s)
print("Min of s:", minimum)

Min of s: 1


In [68]:
# Maximum element of an array
maximum = np.max(s)
print("Max of s:", maximum)

Max of s: 4


#  5.Linear Algebra Functions

In [72]:
#  create a matrix
matrix = np.array([[1,2], [3,4]])

In [73]:
# Determinant of a matrix
determinant = np.linalg.det(matrix)
print("Determinant of matrix:", determinant)

Determinant of matrix: -2.0000000000000004


In [74]:
# Inverse of a matrix
inverse = np.linalg.inv(matrix)
print("Inverse of matrix:\n", inverse)

Inverse of matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]


#  6. Random Sampling Functions

In [75]:
# Generate random values between 0 and 1
random_vals = np.random.rand(3)  # Array of 3 random values between 0 and 1
print("Random values:", random_vals)

Random values: [0.74379522 0.80824201 0.93118597]


In [76]:
# Set seed for reproducibility
np.random.seed(0)

# Generate random values between 0 and 1
random_vals = np.random.rand(3)  # Array of 3 random values between 0 and 1
print("Random values:", random_vals)

Random values: [0.5488135  0.71518937 0.60276338]


In [77]:
# Generate random integers
rand_ints = np.random.randint(0, 10, size=5)  # Random integers between 0 and 10
print("Random integers:", rand_ints)

Random integers: [3 7 9 3 5]


In [78]:
# Set seed for reproducibility
np.random.seed(0)

# Generate random integers
rand_ints = np.random.randint(0, 10, size=5)  # Random integers between 0 and 10
print("Random integers:", rand_ints)

Random integers: [5 0 3 3 7]


#  7. Boolean & Logical Functions

In [79]:
# Check if all elements are True
# all
logical_test = np.array([True, False, True])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [80]:
# Check if all elements are True
logical_test = np.array([True, False, True])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [81]:
# Check if all elements are True
logical_test = np.array([False, False, False])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [86]:
# Check if any elements are True
# any
logical_test = np.array([True, False, True])
any_true = np.any(logical_test)  # Check if any are True
print("Any elements True:", any_true)

Any elements True: True


#  8.Set Operations

In [87]:
# Intersection of two arrays
set_a = np.array([1, 2, 3, 4])
set_b = np.array([3, 4, 5, 6])
intersection = np.intersect1d(set_a, set_b)
print("Intersection of a and b:", intersection)

Intersection of a and b: [3 4]


In [88]:
# Union of two arrays
union = np.union1d(set_a, set_b)
print("Union of a and b:", union)

Union of a and b: [1 2 3 4 5 6]


# 9.Array Attribute Functions

In [89]:
# Array attributes
a = np.array([1, 2, 3])
shape = a.shape  # Shape of the array
size = a.size    # Number of elements
dimensions = a.ndim  # Number of dimensions
dtype = a.dtype   # Data type of the array

print("Shape of a:", shape)
print("Size of a:", size)
print("Number of dimensions of a:", dimensions)
print("Data type of a:", dtype)


Shape of a: (3,)
Size of a: 3
Number of dimensions of a: 1
Data type of a: int64


# 10. Other Functions

In [90]:
# Create a copy of an array
a = np.array([1, 2, 3])
copied_array = np.copy(a)  # Create a copy of array a
print("Copied array:", copied_array)

Copied array: [1 2 3]


In [91]:
# Size in bytes of an array
array_size_in_bytes = a.nbytes  # Size in bytes
print("Size of a in bytes:", array_size_in_bytes)

Size of a in bytes: 24


In [92]:
# Check if two arrays share memory
shared = np.shares_memory(a, copied_array)  # Check if arrays share memory
print("Do a and copied_array share memory?", shared)

Do a and copied_array share memory? False
