# Loops

In [1]:
print('data science')
print('data science')
print('data science')
print('data science')    
print('data science')

data science
data science
data science
data science
data science


In [2]:
i = 1          # initializing

while i<=5:    # condition
    print('data science')
    i = i + 1  # increment

data science
data science
data science
data science
data science


In [3]:
i = 5          # initializing

while i>=1:    # condition
    print('data science')
    i = i - 1  # decrement

data science
data science
data science
data science
data science


In [4]:
i = 1         # initializing
while i<=5:    # condition
    print('data science : ', i)
    i = i + 1  # increment

data science :  1
data science :  2
data science :  3
data science :  4
data science :  5


In [5]:
i = 5          # initializing
while i>=1:    # condition
    print('data science :',i)
    i = i - 1  # decrement

data science : 5
data science : 4
data science : 3
data science : 2
data science : 1


can we use multiple while loop || nested while loop 
to understand nested while indepth understand you can use pycharm debug with f8 option

In [7]:
i = 1

while i<=5:
    print('data science') # when we mention end then new line will not create
    j = 1
    while j<=4:
        print('technology')
        j = j + 1
        
    i = i + 1
    print()
    
    # the output which we got is very lengty but how to make them one line lets refer to below code

data science
technology
technology
technology
technology

data science
technology
technology
technology
technology

data science
technology
technology
technology
technology

data science
technology
technology
technology
technology

data science
technology
technology
technology
technology



In [8]:
i = 1
while i<=5:
    print(' datascience', end = "") # when we mention end then new line will not create
    j = 1
    while j<=4:
        print(' technology', end="")
        j = j + 1
        
    i = i + 1
    print()

 datascience technology technology technology technology
 datascience technology technology technology technology
 datascience technology technology technology technology
 datascience technology technology technology technology
 datascience technology technology technology technology


In [9]:

# lets use while loop usig some numbers
i = 1

while i <= 2 :
    j = 0
    while  j <= 2 :
        print(i*j, end=" ")
        j += 1
    print()
    i += 1

0 1 2 
0 2 4 


In [10]:
# lets use while loop usig some numbers
i = 1
while i <= 4 :
    j = 0
    while  j <= 3 :
        print(i*j, end=" ")
        j += 1
    print()
    i += 1

0 1 2 3 
0 2 4 6 
0 3 6 9 
0 4 8 12 


FOR LOOP  -
normally while loop it work with iteration or certaion some condition but for loop it will work with sequence (list, string,int)

name = 'nit'

for i in name:
    print(i)

In [12]:
name1 = [1,3.5,'hallo'] #i want print the value individualy

for i in name1:
    print(i)

1
3.5
hallo


In [13]:
for i in [2, 3, 7.8, 'hi']:
    print(i)

2
3
7.8
hi


In [14]:
range(5)

range(0, 5)

In [15]:
for i in range(5):
    print(i)

0
1
2
3
4


In [16]:
for i in range(2,5):
    print(i)

2
3
4


In [17]:
for i in range(1,10,3):
    print(i)

1
4
7


In [18]:
# print the value which is divisible by 5 
for i in range(1,21):
    print(i)  

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [19]:
# print the value which is divisible by 5 

for i in range(1,51):
    
    if i%5==0 :
        print(i)

5
10
15
20
25
30
35
40
45
50


In [20]:
# print the value which is divisible by 5 i dont want that value 
for i in range(1,51):
    
    if i%5!=0 :
        print(i)

1
2
3
4
6
7
8
9
11
12
13
14
16
17
18
19
21
22
23
24
26
27
28
29
31
32
33
34
36
37
38
39
41
42
43
44
46
47
48
49


# LETS DISCUSS ABOUT 3 KEYWORDS -- BREAK || CONTINUE || PASS
BREAK STATEMNT - if you apply break statment in a loop then it will end the loop
# Pass = skips block of code( function, class etc)
# Continue= skips 1 step/iteration during loop 
# Break= jumps out of the function/loop

In [22]:
# write the code user ask chocklet from vendor machne write the basic code 

x = int(input('How many choclets you want:?'))

i = 1
while i<=x:
    print('choclet')
    i += 1       

How many choclets you want:? 5


choclet
choclet
choclet
choclet
choclet


- If the user says i need 10 choclet but vending machine dont have 10 choclate & machine has only 5    choclate so what you do on those scenario
- We have 3 choice now  (eiter stop the transaction by you or you can give only 5 choclate) & may be
   vendor machine display the result as we are out of the stock
- Now lets try in the code 

In [24]:
ava = 5 # the machine has only 5 choclet 

x = int(input('How many choclets you want:?'))

i = 1
while i<=x:
    print('choclet')
    i += 1   
# if you check the user wants 10 choclets  but availabe choclet is 5 but we got output as 10 choclet
# in this code we just declare but we dint apply any condition to it 

How many choclets you want:? 5


choclet
choclet
choclet
choclet
choclet


In [25]:
available_choclet = 5 # the machine has only 10 candis 

x = int(input('How many choclets user want:?'))

i = 1
while i<=x:
    
    if i>available_choclet: # we stop the execution but which code execution not entire code , i want to come out of while loop 
        break # break is statement | means jump out of the loop
    print('choclet')
    i += 1   
    
print('bye for now')

How many choclets user want:? 5


choclet
choclet
choclet
choclet
choclet
bye for now


In [26]:
available_choclet = 5 # the machine has only 10 candis 

x = int(input('How many choclets you want:?'))

i = 1
while i<=x:
    
    if i>available_choclet: # we stop the execution but which code execution not entire code , i want to come out of while loop 
        print('out of stock')
        break # break is statement | means jump out of the loop
    print('choclet')
    i += 1   
    
print('bye for now')

How many choclets you want:? 6


choclet
choclet
choclet
choclet
choclet
out of stock
bye for now


In [27]:
for i in range(1,11):
    print(i)

1
2
3
4
5
6
7
8
9
10


- i dont want 11 number i want only 5 number for the range of 1 to 10

In [29]:
for i in range(1,11):
    if i == 6:
       break 
    print(i)

1
2
3
4
5


# in continue loop wont be terminate & exclue the assign number it give you entire output 

for i in range(1,11):
    if i == 3:
        continue 
    print(i)

In [31]:
for i in range(1,11):
    if i == 6:
        continue  
    print('hello :',i)    

hello : 1
hello : 2
hello : 3
hello : 4
hello : 5
hello : 7
hello : 8
hello : 9
hello : 10


In [32]:
#PASS Statement - pass the code & it wont go ( code give you the error)

In [33]:
for i in range(1,11): 

_IncompleteInputError: incomplete input (1593395653.py, line 1)

In [35]:
for i in range(1,11):
    pass

In [ ]:
## you need to print the number from 1 to 50 but dont print the number which is divisible by 3 or 5 

In [36]:
for i in range(1,51):
    
    if i%3 == 0:
    
        print(i)
print('end')    

3
6
9
12
15
18
21
24
27
30
33
36
39
42
45
48
end


In [37]:
for i in range(1,51):
    
    if i%3 == 0:
        continue
    print(i)
print('end')    

1
2
4
5
7
8
10
11
13
14
16
17
19
20
22
23
25
26
28
29
31
32
34
35
37
38
40
41
43
44
46
47
49
50
end


In [38]:
for i in range(1,51):
    
    if i%3 == 0 or i%5 == 0:
        continue
    print(i)
#print('end')    
# it will skip all the value which is divisible by 3 or 5

1
2
4
7
8
11
13
14
16
17
19
22
23
26
28
29
31
32
34
37
38
41
43
44
46
47
49


In [39]:
for i in range(1,50):
    if i%3 == 0 or i%5 == 0:
        continue
    print(i)
print('end')    
# when you apply and you wont get the value which is divisible by both 3 & 5 (15)

1
2
4
7
8
11
13
14
16
17
19
22
23
26
28
29
31
32
34
37
38
41
43
44
46
47
49
end


In [40]:
# i dont want to print the values which are even numbers that means print only odd numbers

for i in range(1,51):
    
    if (i%2 == 0):
        #print('even')
        continue
    else:
        print(i)
print('bye')

1
3
5
7
9
11
13
15
17
19
21
23
25
27
29
31
33
35
37
39
41
43
45
47
49
bye


# PRINTING PATTERN IN PYTHON

In [43]:
print('# # # #')
print('# # # #')
print('# # # #')
print('# # # #')

# # # #
# # # #
# # # #
# # # #


In [44]:
for i in range(1,5):
    i=i+1
    print('# # # # ')

# # # # 
# # # # 
# # # # 
# # # # 


In [45]:
for i in range(1,5):
    if i<=5:
        print('# # # #')

# # # #
# # # #
# # # #
# # # #


In [46]:
for j in range(4):
    print('#')

#
#
#
#


In [47]:
for j in range(4):
    print('# # # #')

# # # #
# # # #
# # # #
# # # #


In [48]:
for j in range(4):
    print('#', end = " ")

# # # # 

In [49]:
for j in range(4):
    print('#', end=" ")

for j in range(4):
    print('#', end=" ")


# # # # # # # # 

In [50]:
for j in range(4):
    print('#', end=" ")
    
print()
    
for j in range(4):
    print('#', end=" ")

# # # # 
# # # # 

In [51]:
for j in range(4):
    print('#', end="  ")
    
print()

for j in range(4):
    print('#', end="  ")

print()

for j in range(4):
    print('#', end="  ")
    
print()

for j in range(4):
    print('#', end="  ")

#  #  #  #  
#  #  #  #  
#  #  #  #  
#  #  #  #  

In [52]:
for i in range(4):
    for j in range(4):
        print('#', end="  ")
    print()
    # pease use debug mode in pycharm

#  #  #  #  
#  #  #  #  
#  #  #  #  
#  #  #  #  


In [53]:
for i in range(4):
    for j in range(i+1):
        print('#', end = " ")
    print()

# 
# # 
# # # 
# # # # 


In [54]:
for i in range(1,5):
    print("# "*i)

# 
# # 
# # # 
# # # # 


In [55]:
for i in range(1,5):
    for j in range(4):
        if i>j:
            print("#",end=" ")
    print()

# 
# # 
# # # 
# # # # 


In [56]:
list(range(5))

[0, 1, 2, 3, 4]

In [57]:
for i in range(4):
    for j in range(i):
        print('#', end="  ")
    print()


#  
#  #  
#  #  #  


In [58]:
for i in range(4):
    for j in range(i+1):
        print('#', end="  ")
    print()

#  
#  #  
#  #  #  
#  #  #  #  


In [59]:
for i in range(4):
    for j in range(4-i):
        print('#', end="  ")
    print()

#  #  #  #  
#  #  #  
#  #  
#  


In [60]:
for i in range(1,5):
    print("# "*(5-i))

# # # # 
# # # 
# # 
# 


- For|Else in python
- In other language for else not supportable but in python it is supportable

eg- lets print the number from 1- 20 & we dont want print number which is divisible by 5

In [62]:
nums = [12,15,18,21,26, 30,40]

for num in nums:
    if num % 5 == 0:
        print(num) 

15
30
40


In [63]:
nums = [12,14,18,21,25,30,35]

for num in nums:
    if num % 5 == 0:
        print(num)  

25
30
35


In [64]:
nums = [12,14,18,21,25,20]

for num in nums:
    if num % 5 == 0:
        print(num)  

25
20


In [65]:
nums = [12,14,18,21,20,25]

for num in nums:
    if num % 5 == 0:
        print(num)  
        break

20


In [66]:
nums = [12,14,18,21,25,20,10]

for num in nums:
    if num % 5 == 0:
        print(num)  
        break

25


In [67]:
nums = [10,14,18,21,5,10]

for num in nums:
    if num % 5 == 0:
        print(num)  
        break #it will print only 1 number then it break  

10


In [70]:
nums = [7,14,18,21,23,27] #hear there is no number which is divisible by 5 we got output as blank

for num in nums:
    if num % 5 == 0:
        print(num)  
        break

In [71]:
nums = [7,14,18,21,23,27,29] #hear there is no number which is divisible by 5 we got output as blank

for num in nums:
    if num % 5 == 0:
        print(num)  
        break
else:
   print('Number Not Found') #every iteration it cheking conditio

Number Not Found


In [72]:
nums = [7,14] #hear there is no number which is divisible by 5 we got output as blank
for num in nums:
    if num % 5 == 0:
        print(num)  
        break
    else:
        print('Number Not Found') #every iteration it cheking condition        

Number Not Found
Number Not Found


In [73]:
nums = [7,14,18,21,23,27] #hear there is no number which is divisible by 5 we got output as blank

for num in nums:
    if num % 5 == 0:
        print(num)  
        break
else:
        print('Number Not Found') # hear else we dont write in if block but we can write in for block only

Number Not Found


In [74]:
nums = [10,14,18,21,20,27] #hear there is no number which is divisible by 5 we got output as blank

for num in nums:
    if num % 5 == 0:
        print(num)  
        break
else:
        print('Not Found')

10


In [75]:
nums = [10,14,18,21,20,27,30] #hear there is no number which is divisible by 5 we got output as blank

for num in nums:
    if num % 5 == 0:
        print(num)  
        #break
else:
        print('Not Found')

10
20
30
Not Found


In [76]:
nums = [10,14,18,21,20,27] #hear there is no number which is divisible by 5 we got output as blank
for num in nums:
    if num % 5 == 0:
        print(num)  
        break
else:
        print('Not Found')

10


- prime number - how to check given number is prime number or not

num = 14

for i in range(2,num):
    if num % i == 0:
        print('Not prime Number')
        break
else:
    print('Prime Number')

In [78]:
num = 13

for i in range(2,num):
    if num % i == 0:
        print('Not prime Number')
        break
else:
    print('Prime Number')

Prime Number


# Array In Python

In [79]:
from array import * 
arr = array('i',[])

n = int(input('Enter the length of the array'))

for i in range(5):
    x = int(input('Enter the next value'))
    arr.append(x)
print(arr)

Enter the length of the array 45
Enter the next value 45
Enter the next value 4
Enter the next value 45
Enter the next value 45
Enter the next value 4


array('i', [45, 4, 45, 45, 4])


In [80]:
from array import * 
arr = array('i',[])

n = int(input('Enter the length of the array'))

for i in range(5):
    x = int(input('Enter the next value'))
    arr.append(x)
print(arr)

Enter the length of the array 12
Enter the next value 23
Enter the next value 45
Enter the next value 67
Enter the next value 76
Enter the next value 3


array('i', [23, 45, 67, 76, 3])


In [82]:
## from array import * 
arr = array('i',[])

n = input('Enter the length of the array')

for i in range(5):
    x = input('Enter the next value')
    arr.append(x)
print(arr)

Enter the length of the array 12
Enter the next value 34


TypeError: 'str' object cannot be interpreted as an integer

In [83]:
# Way of creating array using numpy

In [84]:
from numpy import *
arr = array([1,2,3,4,5])
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [85]:
print(arr.dtype)

int64


In [86]:
arr2 = array([1,2,3,4,5.9],float)
arr2

array([1. , 2. , 3. , 4. , 5.9])

In [87]:
arr3 = array([1,2,3,4,5.6],int)
arr3

array([1, 2, 3, 4, 5])

In [88]:
import numpy as np

In [89]:
arr4 = np.linspace(0, 16, 10) # break the code between 10 spaces between 0 to 16 but why decimal becuase we break into parts thats why it is floats
arr4

array([ 0.        ,  1.77777778,  3.55555556,  5.33333333,  7.11111111,
        8.88888889, 10.66666667, 12.44444444, 14.22222222, 16.        ])

In [90]:
arr5 = np.arange(0,10,2) # arange - as range
arr5

array([0, 2, 4, 6, 8])

In [91]:
arr6 = np.zeros(5)
arr6

array([0., 0., 0., 0., 0.])

In [92]:
arr7 = np.ones(5)
arr7

array([1., 1., 1., 1., 1.])

In [ ]:
import tkinter as tk
# Function to be called when the button is clicked
def on_button_click():
    label.config(text="Button clicked!")

# Create the main application window
root = tk.Tk()
root.title("Simple Tkinter App")

# Create a label widget
label = tk.Label(root, text="Hello, Tkinter!")
label.pack(pady=20)

# Create a button widget
button = tk.Button(root, text="Click Me", command=on_button_click)
button.pack(pady=20)

# Run the application
root.mainloop()

In [ ]:
import tkinter as tk
from tkinter import messagebox

# Function to be called when the button is clicked
def on_button_click():
    user_input = entry.get()
    messagebox.showinfo("Information", f"You entered: {user_input}")

# Create the main application window
root = tk.Tk()
root.title("Simple Tkinter App")

# Create a label widget
label = tk.Label(root, text="Enter something:")
label.pack(pady=10)

# Create a text entry widget
entry = tk.Entry(root, width=30)
entry.pack(pady=10)

# Create a button widget
button = tk.Button(root, text="Submit", command=on_button_click)
button.pack(pady=10)

# Run the application
root.mainloop()


In [ ]:
__name__